name = "CountTimeSeries"
uuid = "f648fdee-df8a-4cb4-ac79-58ced742ae0a"
authors = ["Manuel Stapper"]
version = "0.1.0"

[compat]
julia = "1"
Calculus = "0.5.1"
Distributions = "0.23.11"
Optim = "1.2.0"
Plots = "1.6.4"
Roots = "1.0.5"
StatsBase = "0.33.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
